# Generated by Django 5.1.1 on 2024-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='products/images/'),
        ),
    ]
